# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termcade < Formula
  desc "Classic arcade games in your terminal, built with Go and Bubble Tea"
  homepage "https://github.com/kacheo/termcade"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kacheo/termcade/releases/download/v0.1.0/termcade_0.1.0_darwin_amd64.tar.gz"
      sha256 "c837baa688102f0a189dbc4243afdb2766f79cd3d0c7a657891926a4321a61a4"

      define_method(:install) do
        bin.install "termcade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kacheo/termcade/releases/download/v0.1.0/termcade_0.1.0_darwin_arm64.tar.gz"
      sha256 "8f1c4ff0683e59e45a515cc9bae8a2dbfb40782f076d4b7184428d5adccf383a"

      define_method(:install) do
        bin.install "termcade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kacheo/termcade/releases/download/v0.1.0/termcade_0.1.0_linux_amd64.tar.gz"
      sha256 "0e80b6bef1f194d2d3c91ece1a03d0e0984ef6fe72beac7bdf8dae6254f8a88d"
      define_method(:install) do
        bin.install "termcade"
      end
    end
  end

  test do
    system "#{bin}/termcade", "--version"
  end
end
